CREATE TABLE WORK 
(
  WORK_DATE DATE NOT NULL 
, STUDENT_EMAIL_FK VARCHAR2(20) NOT NULL 
, WORK_TEXT VARCHAR2(200) NOT NULL 
, WORK_MARK NUMBER 
);


ALTER TABLE WORK
ADD CONSTRAINT work_PK PRIMARY KEY (WORK_DATE,STUDENT_EMAIL_FK); -- primary key

ALTER TABLE WORK
ADD CONSTRAINT work_FK FOREIGN KEY (STUDENT_EMAIL_FK) REFERENCES STUDENT (student_email);